platform :ios, '8.0'

use_frameworks!

target 'Guardioes' do

  pod 'Alamofire', '~> 1.2'
  # pod 'Google/CloudMessaging'
  # pod 'Google/SignIn'
  pod 'OCMapper', '~> 2.1'

end

target 'GuardioesTests' do

end
